// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nedis.Server.Modules.Identity.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nedis.Server.Modules.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nedis.Server.Modules.Identity.Domain.GlobalIdentity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("GlobalIdentities", "identity");
                });

            modelBuilder.Entity("Nedis.Server.Modules.Identity.Domain.LocalCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("LocalCredentials", "identity");
                });

            modelBuilder.Entity("Nedis.Server.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Nedis.Server.Modules.Identity.Domain.GlobalIdentity", b =>
                {
                    b.HasOne("Nedis.Server.Modules.Identity.Domain.User", "User")
                        .WithOne("GlobalIdentity")
                        .HasForeignKey("Nedis.Server.Modules.Identity.Domain.GlobalIdentity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nedis.Server.Modules.Identity.Domain.LocalCredential", b =>
                {
                    b.HasOne("Nedis.Server.Modules.Identity.Domain.User", "User")
                        .WithOne("LocalCredential")
                        .HasForeignKey("Nedis.Server.Modules.Identity.Domain.LocalCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nedis.Server.Modules.Identity.Domain.User", b =>
                {
                    b.Navigation("GlobalIdentity");

                    b.Navigation("LocalCredential");
                });
#pragma warning restore 612, 618
        }
    }
}
